name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Simple JS Action
        run: |
            pwd
            ls -la
        id: greet

