name: Create secret commit

on: [ push ]

jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available to all steps in log-env job
    steps:
      - name: Log Env Variables
        env: 
          STEP_ENV: Available only here
        run: |
        
